<?php
namespace app\models;

use Yii;


class OrderSearchProvider extends \yii\data\ActiveDataProvider {

    public $empty_rows_count = 0;

    public function getModels() {

        $models = parent::getModels();

        for($i = 0; $i < $this->empty_rows_count; $i++) {
            $models[] = new OrderSearch();
        }

        return $models;
    }

    public function getKeys()
    {
        $keys =  parent::getKeys(); // TODO: Change the autogenerated stub

        for($i = 0; $i < $this->empty_rows_count; $i++) {
            $keys[] = 0;
        }

        return $keys;
    }
}